name: Build freeldr only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build in Arch Linux Docker
      run: |
        docker pull archlinux:latest  # Pull the latest Arch Linux image
        docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest /bin/bash -c "
        set -euo pipefail
        echo 'Updating Arch Linux repositories...'
        pacman -Syu --noconfirm || { echo 'Failed to update Arch repositories'; exit 1; }
        
        echo 'Installing dependencies...'
        pacman -S --noconfirm ninja lld mingw-w64-gcc cmake gcc git \
        bison flex || { echo 'Failed to install dependencies'; exit 1; }
        
        echo 'Configuring the build...'
        ROS_ARCH=i386 ./configure.sh || { echo 'Configure failed'; exit 1; }
        
        echo 'Building freeldr...'
        cd output-MinGW-i386
        ninja freeldr || { echo 'Freeldr build failed'; exit 1; }
        
        echo 'Building dosmbr...'
        ninja boot/freeldr/bootsect/dosmbr || { echo 'dosmbr build failed'; exit 1; }
        
        echo 'Build complete'
        "

    - name: Upload freeldr.sys and dosmbr
      uses: actions/upload-artifact@v4.6.1
      with:
        name: freeldr-artifacts
        path: |
          output-MinGW-i386/boot/freeldr/freeldr/freeldr.sys

    - name: Upload freeldr.sys to GitHub Releases
      uses: softprops/action-gh-release@v1
      with: 
        files: "output-MinGW-i386/boot/freeldr/freeldr/freeldr.sys"  # This grabs freeldr.sys
        tag_name: latest
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
