name: Build freeldr only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get deps
      run: sudo apt install gcc ninja-build flex bison cmake llvm
    - name: Configure
      run: ROS_ARCH=i386 ./configure.sh
    - name: Build
      run: |
        cd output-MinGW-i386
        ninja freeldr
        ninja boot/freeldr/bootsect/dosmbr
        cd ..
    - name: Upload freeldr.sys
      uses: actions/upload-artifact@v4.6.1
      with:
        path: |
          output-MinGW-i386/boot/freeldr/freeldr/freeldr.sys
          output-MinGW-i386/boot/freeldr/bootsect/dosmbr.bin
