name: Build freeldr only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get deps
      run: sudo apt install gcc ninja-build flex bison cmake llvm
    - name: Configure
      run: chmod +x ./configure.sh ; ./configure.sh
    - name: make
      run: ninja freeldr
