name: Build freeldr only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get deps
      run: |
        sudo apt install gcc ninja-build flex bison cmake llvm
        - name: Get RosBE build specifics
    - name: Get ROSBE init stuff
      id: get_rosbe_spec
      run: |
        gcc -march=native -Q --help=target | grep "\-march= " | awk '{print $NF}'
        echo march-sha=$(gcc -march=native -Q --help=target | sha1sum | awk '{print $1}') >> $GITHUB_OUTPUT
        echo git-sha=$(git ls-remote https://github.com/zefklop/RosBE.git | grep unix_amd64 | awk '{print $1}') >> $GITHUB_OUTPUT
        wget https://gist.githubusercontent.com/zefklop/b2d6a0b470c70183e93d5285a03f5899/raw/build_rosbe_ci.sh
    - name: Get RosBE
      id: get_rosbe
      uses: actions/cache@v4
      with:
        path: RosBE-CI
        key: RosBE-CI-${{runner.os}}-${{steps.get_rosbe_spec.outputs.march-sha}}-${{steps.get_rosbe_spec.outputs.git-sha}}-${{hashfiles('./build_rosbe_ci.sh')}}
    - name: Compile RosBE
      if: ${{ steps.get_rosbe.outputs.cache-hit != 'true' }}
      run: |
        chmod +x build_rosbe_ci.sh
        ./build_rosbe_ci.sh ${{github.workspace}}/RosBE-CI
    - name: Configure
      run: chmod +x ./configure.sh ; ./configure.sh
    - name: make
      run: ninja freeldr
