name: Build freeldr only

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get deps
      run: |
        sudo apt-get install gcc ninja-build flex bison cmake llvm gzip libmpc3 docker
    - name: Build
      run: |
          docker pull archlinux:latest  # Pull the latest Arch Linux image
          docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest /bin/bash -c "
          # Update Arch Linux repositories
          pacman -Syu --noconfirm;
          # Install MinGW-w64 and required dependencies
          pacman -S --noconfirm mingw-w64-i686-gcc mingw-w64-i686-g++;
          ROS_ARCH=i386 ./configure.sh
          cd output-MinGW-i386
          ninja freeldr
          ninja boot/freeldr/bootsect/dosmbr
          cd ..
          "
    - name: Upload freeldr.sys
      uses: actions/upload-artifact@v4.6.1
      with:
        path: |
          output-MinGW-i386/boot/freeldr/freeldr/freeldr.sys
          output-MinGW-i386/boot/freeldr/bootsect/dosmbr.bin
